package com.noker.mis.dao;

import com.noker.mis.model.Manger;

public interface MangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mangerName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    int insert(Manger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    int insertSelective(Manger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    Manger selectByPrimaryKey(String mangerName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Manger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manger
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Manger record);
}