package com.noker.mis.dao;

import java.util.List;

import com.noker.mis.model.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

	List<Product> selectspyl(Product productInfo);

	List<Product> selectmrhl(Product productInfo);

	List<Product> selectlyfs(Product productInfo);

	List<Product> selectjtqj(Product productInfo);

	List<Product> selectsxsg(Product productInfo);

	List<Product> selectmyyp(Product productInfo);

	List<Product> selectmyypAll(Product productInfo);

	List<Product> selectsxsgAll(Product productInfo);

	List<Product> selectjtqjAll(Product productInfo);

	List<Product> selectlyfsAll(Product productInfo);

	List<Product> selectmrhlAll(Product productInfo);

	List<Product> selectspylAll(Product productInfo);

	List<Product> searchTitleByKey(String key);

	List<Product> selectAllProduct(Product productInfo);
}