package com.noker.mis.dao;

import java.util.List;

import com.noker.mis.bean.ProductCar;
import com.noker.mis.model.Product;
import com.noker.mis.model.Shopping;

public interface ShoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    int insert(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    int insertSelective(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    Shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shopping record);

	List<ProductCar> account(String phone);

	Integer count(String phone);
}